export const IMAGE_UPLOAD = "image_upload"
export const FORM_ENTRY = "form_entry"
export const FORM_CLEAR = "form_clear"
export const FORM_ENTRY_ARRAY = "array_form_entry"

export const ERR_PWD_MISMATCH = "Password mismatch"
export const ERR_PWD_SMALL = "Password too small"
export const ERR_PWD_CASE = "Password should use both cases"
export const ERR_PWD_NUMERIC = "Password should contain numbers"
export const ERR_MAIL_INVALID = "Email is invalid"
export const ERR_FIELD_RQD = "Field is required"
export const ERR_RESET = "reset error"
